In [5]:
#sets
S1 = {1,2,3}
S2 = {5,6,2,1}

S1.intersection(S2)

{1, 2}

In [4]:
S1.union(S2)

{1, 2, 3, 5, 6}

In [6]:
S1 = {'A', 'B', 'C', 'C', 'D'}
print(S1) #cannot have multiple values of same input and it does have any order of printing.

{'C', 'A', 'B', 'D'}


In [7]:
S2 = {}
print(type(S2))

<class 'dict'>


In [15]:
S3 = set{}
S3

SyntaxError: invalid syntax (<ipython-input-15-59f1563f2d79>, line 1)

In [11]:
#random library
import random as r

In [19]:
print(r.random()) ##0 se 1 ke beech mein koi bhi random value de deta hai

0.008465472411741337


In [23]:
print(r.randint(100,2000000000)) #you can put any range in between the brackets and it would print any random integer in between them 
print(r.randint(100,2000000000))
print(r.randint(100,2000000000))
print(r.randint(100,2000000000))

1119847239
700783612
330333105
1997894697


In [26]:
li = [2,3,1,9,7,4]

print(r.sample(li,2)) #2 ka matlab hai list mein se kitne random numbers chahiye

[4, 1]


In [28]:
print(r.sample(range(0,1000),5)) #last mein 5 ka matlab hai ki range se 5 random numbers uthane hain

[216, 836, 139, 656, 373]


In [35]:
import string as s

new = set(s.ascii_letters) #saare letters ko ek set mein daal diya
new

{'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [6]:
#6 digit pssword generator
import random as r 
import string as s
passwd = r.sample(s.ascii_letters,6)
passwd

['u', 'N', 's', 'L', 'W', 'Z']

In [9]:
paswd = "".join(passwd) #"" ke andar kuch nahi likha taaki saare alphabets ek saath directly jud jayein, agar us mein - laga doon to vo is sign ke saath jud jayenge.
paswd

'uNsLWZ'

In [40]:
# 6 digit OTP generator
s.digits

'0123456789'

In [45]:
var = r.sample(s.digits,6)
var

['1', '4', '2', '7', '8', '6']

In [46]:
otp = "".join(var)
otp

'142786'

In [48]:
spl = "!@#$%^&*~`+=_-|\?/:;"

mixpwd = r.sample(spl + s.ascii_letters + s.digits, 12)
mixpwd

['B', '_', '|', 'c', '2', 'e', '!', ';', 'O', 'd', '?', '#']

In [49]:
mixpassword = "".join(mixpwd)
mixpassword

'B_|c2e!;Od?#'

In [50]:
#numpy library
import numpy as np

In [51]:
li = [1,2,3,4,5,6]
arr = np.array(li)
print(arr)

[1 2 3 4 5 6]


In [52]:
arr.shape

(6,)

In [55]:
li = [[1,2],[3,4],[5,6]]
arr = np.array(li)
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [56]:
arr.shape

(3, 2)

In [57]:
arr.shape = (2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
st = np.arange(9) # 0 se lekar 9 tak ka ek array bana dega 
st

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
st.shape = (3,3)
st

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
st.ndim

2

In [65]:
x = np.zeros(6)
x

array([0., 0., 0., 0., 0., 0.])

In [67]:
x.shape = (2,3)
x

array([[0., 0., 0.],
       [0., 0., 0.]])